<?php

declare(strict_types=1);

/*
 * GENERATED by openapi-laravel. Do not edit.
 * Re-run the generator to refresh routes from the spec.
 */

use CodeWithAgents\OpenApiLaravel\Examples\Petstore\Http\Controllers\Api\PetController;
use CodeWithAgents\OpenApiLaravel\Examples\Petstore\Http\Controllers\Api\StoreController;
use CodeWithAgents\OpenApiLaravel\Examples\Petstore\Http\Controllers\Api\UserController;
use Illuminate\Support\Facades\Route;

Route::post('/pet', [PetController::class, 'addPet'])->name('addPet');
Route::put('/pet', [PetController::class, 'updatePet'])->name('updatePet');
Route::get('/pet/findByStatus', [PetController::class, 'findPetsByStatus'])->name('findPetsByStatus');
Route::get('/pet/findByTags', [PetController::class, 'findPetsByTags'])->name('findPetsByTags');
Route::get('/pet/{petId}', [PetController::class, 'getPetById'])->name('getPetById');
Route::post('/pet/{petId}', [PetController::class, 'updatePetWithForm'])->name('updatePetWithForm');
Route::delete('/pet/{petId}', [PetController::class, 'deletePet'])->name('deletePet');
Route::post('/pet/{petId}/uploadImage', [PetController::class, 'uploadFile'])->name('uploadFile');
Route::get('/store/inventory', [StoreController::class, 'getInventory'])->name('getInventory');
Route::post('/store/order', [StoreController::class, 'placeOrder'])->name('placeOrder');
Route::get('/store/order/{orderId}', [StoreController::class, 'getOrderById'])->name('getOrderById');
Route::delete('/store/order/{orderId}', [StoreController::class, 'deleteOrder'])->name('deleteOrder');
Route::post('/user', [UserController::class, 'createUser'])->name('createUser');
Route::post('/user/createWithList', [UserController::class, 'createUsersWithListInput'])->name('createUsersWithListInput');
Route::get('/user/login', [UserController::class, 'loginUser'])->name('loginUser');
Route::get('/user/logout', [UserController::class, 'logoutUser'])->name('logoutUser');
Route::get('/user/{username}', [UserController::class, 'getUserByName'])->name('getUserByName');
Route::put('/user/{username}', [UserController::class, 'updateUser'])->name('updateUser');
Route::delete('/user/{username}', [UserController::class, 'deleteUser'])->name('deleteUser');
