<?php

declare(strict_types=1);

/*
 * GENERATED by openapi-laravel. Do not edit.
 * Re-run the generator to refresh routes from the spec.
 */

use CodeWithAgents\OpenApiLaravel\Tests\Feature\Example\Writable\Http\WidgetsController;
use Illuminate\Support\Facades\Route;

Route::post('/widgets', [WidgetsController::class, 'createWidget'])->name('createWidget');
Route::get('/widgets/{widgetId}', [WidgetsController::class, 'getWidgetById'])->name('getWidgetById');
