<?php

declare(strict_types=1);

namespace CodeWithAgents\OpenApiLaravel\Tests;

use CodeWithAgents\OpenApiLaravel\OpenApiLaravelServiceProvider;
use Illuminate\Foundation\Application;
use Orchestra\Testbench\TestCase as Orchestra;
use Spatie\LaravelData\LaravelDataServiceProvider;

abstract class TestCase extends Orchestra
{
    /**
     * @return array<int, class-string>
     */
    protected function getPackageProviders($app): array
    {
        return [
            LaravelDataServiceProvider::class,
            OpenApiLaravelServiceProvider::class,
        ];
    }

    /**
     * Controllers and routes are generated by default, and the package config
     * points them at app_path()/base_path(), which in tests is the shared
     * testbench skeleton. Redirect both to a per-test temp dir so default-on
     * runs never write into the skeleton; tests asserting on scaffold output
     * set their own explicit paths anyway.
     *
     * @param  Application  $app
     */
    protected function defineEnvironment($app): void
    {
        $base = sys_get_temp_dir().'/oal_scaffold_'.uniqid();

        $app['config']->set('openapi-laravel.controllers.path', $base.'/Http/Controllers/Api');
        $app['config']->set('openapi-laravel.routes.path', $base.'/routes/api.generated.php');
    }
}
