<?php

declare(strict_types=1);

namespace CodeWithAgents\OpenApiLaravel\Emitter\Server;

use CodeWithAgents\OpenApiLaravel\Emitter\GeneratedFile;

/**
 * Emits a single routes file from the collected operation descriptors: one
 * Route:: line per spec operation, pointing at the concrete controller class
 * (the user's subclass, not the abstract). Because the routing table derives
 * from the spec, path-level spec/code drift is structurally impossible.
 *
 * Output is deterministic: imports sorted and unique, route lines in the
 * descriptor order (already path then HTTP method).
 */
final class RouteGenerator
{
    public function __construct(
        private readonly ServerOptions $options,
    ) {}

    /**
     * @param  list<OperationDescriptor>  $descriptors
     */
    public function generate(array $descriptors): GeneratedFile
    {
        $controllerImports = [];
        foreach ($descriptors as $descriptor) {
            $controllerImports[] = $this->options->controllerNamespace.'\\'.$descriptor->controllerClass;
        }
        $controllerImports = array_values(array_unique($controllerImports));
        sort($controllerImports);

        $uses = ['use Illuminate\\Support\\Facades\\Route;'];
        foreach ($controllerImports as $fqcn) {
            $uses[] = 'use '.$fqcn.';';
        }
        sort($uses);

        $lines = [];
        foreach ($descriptors as $descriptor) {
            $lines[] = 'Route::'.$descriptor->httpMethod."('".$this->escape($descriptor->path)."', ["
                .$descriptor->controllerClass."::class, '".$this->escape($descriptor->methodName)."']);";
        }

        $header = "<?php\n\ndeclare(strict_types=1);\n\n"
            ."/*\n"
            ." * GENERATED by openapi-laravel. Do not edit.\n"
            ." * Re-run the generator to refresh routes from the spec.\n"
            ." */\n\n";

        $body = $lines === [] ? '' : implode("\n", $lines)."\n";

        return new GeneratedFile('api.generated', $header.implode("\n", $uses)."\n\n".$body);
    }

    private function escape(string $value): string
    {
        return str_replace(['\\', "'"], ['\\\\', "\\'"], $value);
    }
}
