<?php

declare(strict_types=1);

namespace CodeWithAgents\OpenApiLaravel\Emitter\Server;

use CodeWithAgents\OpenApiLaravel\Emitter\GeneratedFile;

/**
 * Emits a single routes file from the collected operation descriptors: one
 * Route:: line per spec operation, pointing at the concrete controller class
 * (the user's subclass, not the abstract). Because the routing table derives
 * from the spec, path-level spec/code drift is structurally impossible.
 *
 * Every route carries a `->name()` that follows the controller method name
 * (issue #71): the operationId-derived identifier by default, or the
 * conventional index/show/store/update/destroy under the opt-in
 * --laravel-conventions (issue #94). Names are unique across the table, so
 * the route() helper, URL generation, and route-based authorization can
 * target generated routes. When the config sets
 * routes.middleware and/or routes.prefix, the routes are wrapped in one
 * Route::middleware(...)->prefix(...)->group(...) block; with neither set the
 * output stays the flat list it always was.
 *
 * An operation whose selected success response declares a non-200 status
 * (201, 202, 204, ...) additionally gets the inlined RespondsWithStatus
 * middleware with that code as its parameter (issue #64), so the scaffold
 * produces the spec-declared status while the controller keeps returning the
 * plain Data object (or nothing, for 204).
 *
 * An operation whose spec security resolves to mapped middleware through
 * security.middleware_map (issue #77) gets one ->middleware([...]) call with
 * those names; the status-enforcing entry folds into the same array when both
 * apply.
 *
 * Output is deterministic: imports sorted and unique, route lines in the
 * descriptor order (already path then HTTP method).
 *
 * @internal
 */
final readonly class RouteGenerator
{
    public function __construct(
        private ServerOptions $options,
    ) {}

    /**
     * @param  list<OperationDescriptor>  $descriptors
     */
    public function generate(array $descriptors): GeneratedFile
    {
        $controllerImports = [];
        foreach ($descriptors as $descriptor) {
            $controllerImports[] = $this->options->controllerNamespace.'\\'.$descriptor->controllerClass;
        }
        $controllerImports = array_values(array_unique($controllerImports));
        sort($controllerImports);

        $uses = ['use Illuminate\\Support\\Facades\\Route;'];
        foreach ($controllerImports as $fqcn) {
            $uses[] = 'use '.$fqcn.';';
        }

        // The status-enforcing middleware (issue #64) is imported only when at
        // least one route actually attaches it, so no `use` goes unused.
        $needsStatusMiddleware = false;

        $lines = [];
        foreach ($descriptors as $descriptor) {
            $line = 'Route::'.$descriptor->httpMethod."('".$this->escape($descriptor->path)."', ["
                .$descriptor->controllerClass."::class, '".$this->escape($descriptor->methodName)."'])"
                ."->name('".$this->escape($descriptor->routeName)."')";

            if ($descriptor->securityMiddleware === []) {
                // No security middleware: the historical single-argument form,
                // byte-identical to the pre-#77 output.
                if ($descriptor->needsStatusMiddleware()) {
                    $needsStatusMiddleware = true;
                    $line .= '->middleware(RespondsWithStatus::class.\':'.$descriptor->successStatus.'\')';
                }
            } else {
                // Security middleware (issue #77), with the status-enforcing
                // entry (issue #64) folded into the same array so each route
                // carries exactly one ->middleware([...]) call.
                $entries = array_map(
                    fn (string $name): string => "'".$this->escape($name)."'",
                    $descriptor->securityMiddleware,
                );
                if ($descriptor->needsStatusMiddleware()) {
                    $needsStatusMiddleware = true;
                    $entries[] = 'RespondsWithStatus::class.\':'.$descriptor->successStatus.'\'';
                }
                $line .= '->middleware(['.implode(', ', $entries).'])';
            }

            $lines[] = $line.';';
        }

        if ($needsStatusMiddleware) {
            $uses[] = 'use '.$this->options->dataNamespace.'\\Support\\RespondsWithStatus;';
        }
        sort($uses);

        $header = "<?php\n\ndeclare(strict_types=1);\n\n"
            ."/*\n"
            ." * GENERATED by openapi-laravel. Do not edit.\n"
            ." * Re-run the generator to refresh routes from the spec.\n"
            ." */\n\n";

        $body = $this->body($lines);

        return new GeneratedFile('api.generated', $header.implode("\n", $uses)."\n\n".$body);
    }

    /**
     * Render the route lines, wrapped in a Route::middleware/prefix group when
     * the options configure either (issue #71). No middleware and no prefix
     * keeps the historical flat list, byte-identical to before.
     *
     * @param  list<string>  $lines
     */
    private function body(array $lines): string
    {
        if ($lines === []) {
            return '';
        }

        $group = $this->groupChain();
        if ($group === null) {
            return implode("\n", $lines)."\n";
        }

        $indented = array_map(static fn (string $line): string => '    '.$line, $lines);

        return $group."->group(function (): void {\n".implode("\n", $indented)."\n});\n";
    }

    /**
     * The `Route::middleware([...])->prefix('...')` chain opening the group,
     * or null when neither middleware nor a prefix is configured. The prefix
     * treats '' like null so an empty config key cannot emit a useless group.
     */
    private function groupChain(): ?string
    {
        $calls = [];

        if ($this->options->routeMiddleware !== []) {
            $middleware = array_map(
                fn (string $name): string => "'".$this->escape($name)."'",
                $this->options->routeMiddleware,
            );
            $calls[] = 'middleware(['.implode(', ', $middleware).'])';
        }

        $prefix = $this->options->routePrefix;
        if ($prefix !== null && $prefix !== '') {
            $calls[] = "prefix('".$this->escape($prefix)."')";
        }

        return $calls === [] ? null : 'Route::'.implode('->', $calls);
    }

    private function escape(string $value): string
    {
        return str_replace(['\\', "'"], ['\\\\', "\\'"], $value);
    }
}
