<?php

declare(strict_types=1);

/*
 * GENERATED by openapi-laravel. Do not edit.
 * Re-run the generator to refresh routes from the spec.
 */

use App\Http\Controllers\Api\PetController;
use App\Http\Controllers\Api\StoreController;
use App\Http\Controllers\Api\UserController;
use Illuminate\Support\Facades\Route;

Route::post('/pet', [PetController::class, 'addPet'])->name('addPet');
Route::put('/pet', [PetController::class, 'updatePet'])->name('updatePet');
Route::get('/pet/findByStatus', [PetController::class, 'findPetsByStatus'])->name('findPetsByStatus');
Route::get('/pet/findByTags', [PetController::class, 'findPetsByTags'])->name('findPetsByTags');
Route::get('/pet/{petId}', [PetController::class, 'show'])->name('show');
Route::post('/pet/{petId}', [PetController::class, 'updatePetWithForm'])->name('updatePetWithForm');
Route::delete('/pet/{petId}', [PetController::class, 'destroy'])->name('destroy');
Route::post('/pet/{petId}/uploadImage', [PetController::class, 'uploadFile'])->name('uploadFile');
Route::get('/store/inventory', [StoreController::class, 'index'])->name('index');
Route::post('/store/order', [StoreController::class, 'store'])->name('store');
Route::get('/store/order/{orderId}', [StoreController::class, 'show'])->name('show_2');
Route::delete('/store/order/{orderId}', [StoreController::class, 'destroy'])->name('destroy_2');
Route::post('/user', [UserController::class, 'createUser'])->name('createUser');
Route::post('/user/createWithList', [UserController::class, 'createUsersWithListInput'])->name('createUsersWithListInput');
Route::get('/user/login', [UserController::class, 'loginUser'])->name('loginUser');
Route::get('/user/logout', [UserController::class, 'logoutUser'])->name('logoutUser');
Route::get('/user/{username}', [UserController::class, 'show'])->name('show_3');
Route::put('/user/{username}', [UserController::class, 'update'])->name('update');
Route::delete('/user/{username}', [UserController::class, 'destroy'])->name('destroy_3');
