<?php

declare(strict_types=1);

use CodeWithAgents\OpenApiLaravel\Emitter\ModelGenerator;
use CodeWithAgents\OpenApiLaravel\Emitter\Server\OperationCollector;
use CodeWithAgents\OpenApiLaravel\Emitter\Server\RouteGenerator;
use CodeWithAgents\OpenApiLaravel\Emitter\Server\ServerOptions;
use CodeWithAgents\OpenApiLaravel\Parser\SpecParser;

function generateRoutes(): string
{
    $doc = (new SpecParser)->parseFile(__DIR__.'/../../../Fixtures/server/petstore.yaml');
    $generator = new ModelGenerator;
    $generator->generate($doc);
    $options = new ServerOptions;
    $descriptors = (new OperationCollector($options, $generator->registry()))->collect($doc);

    return (new RouteGenerator($options))->generate($descriptors)->code;
}

it('names the routes file api.generated', function () {
    $doc = (new SpecParser)->parseFile(__DIR__.'/../../../Fixtures/server/petstore.yaml');
    $generator = new ModelGenerator;
    $generator->generate($doc);
    $options = new ServerOptions;
    $descriptors = (new OperationCollector($options, $generator->registry()))->collect($doc);

    $file = (new RouteGenerator($options))->generate($descriptors);

    expect($file->className)->toBe('api.generated')
        ->and($file->filename())->toBe('api.generated.php');
});

it('emits a generated-do-not-edit header and the Route facade import', function () {
    $code = generateRoutes();

    expect($code)->toContain('GENERATED by openapi-laravel. Do not edit.')
        ->and($code)->toContain('use Illuminate\Support\Facades\Route;');
});

it('emits one Route line per operation pointing at the concrete controller', function () {
    $code = generateRoutes();

    expect($code)->toContain("Route::get('/pets', [PetController::class, 'listPets']);")
        ->and($code)->toContain("Route::post('/pets', [PetController::class, 'createPet']);")
        ->and($code)->toContain("Route::get('/pets/{petId}', [PetController::class, 'getPetById']);")
        ->and($code)->toContain("Route::delete('/pets/{petId}', [PetController::class, 'deletePet']);")
        ->and($code)->toContain("Route::get('/health', [UntaggedController::class, 'getHealth']);");
});

it('imports the concrete controllers (not the abstracts), sorted and unique', function () {
    $code = generateRoutes();

    expect($code)->toContain('use App\Http\Controllers\Api\PetController;')
        ->and($code)->toContain('use App\Http\Controllers\Api\UntaggedController;')
        ->and($code)->not->toContain('AbstractPetController')
        ->and(substr_count($code, 'use App\Http\Controllers\Api\PetController;'))->toBe(1);
});

it('passes the spec path through verbatim, including braces', function () {
    expect(generateRoutes())->toContain("'/pets/{petId}'");
});

it('is deterministic and syntactically valid PHP', function () {
    expect(generateRoutes())->toBe(generateRoutes());
    expect(fn () => token_get_all(generateRoutes(), TOKEN_PARSE))->not->toThrow(Throwable::class);
});
