<?php

declare(strict_types=1);

namespace CodeWithAgents\OpenApiLaravel\Console;

use CodeWithAgents\OpenApiLaravel\Emitter\GenerationException;
use CodeWithAgents\OpenApiLaravel\Parser\ParseException;

/**
 * Framework-free entry point: runs the generator from CLI arguments without a
 * Laravel container, so non-Laravel projects and CI can use it via
 * vendor/bin/openapi-laravel. The Laravel artisan commands and this class share
 * the same parser/generator/writer core (GenerationPlanner), so generate and
 * check can never compute a different file set than each other.
 *
 * Subcommands:
 *   openapi-laravel [generate] --spec=... --output=...   write the generated files
 *   openapi-laravel check --spec=... --output=...        verify disk matches the spec
 *
 * `generate` is the default when no subcommand is given, preserving the
 * historical `openapi-laravel --spec=... --output=...` invocation.
 *
 * Settings come from three layers with strict precedence: CLI flags beat the
 * JSON config file (`openapi-laravel.json` in the working directory, or
 * `--config=<path>`), and the config file beats the built-in defaults. The
 * full output (models, controllers, routes) is generated by default;
 * `--no-controllers` / `--no-routes` opt out per run.
 *
 * @internal
 */
final class StandaloneApplication
{
    private const EXIT_OK = 0;

    private const EXIT_DRIFT = 1;

    private const EXIT_ERROR = 2;

    /**
     * @param  list<string>  $argv
     */
    public function run(array $argv): int
    {
        [$subcommand, $argv] = $this->splitSubcommand($argv);

        return $subcommand === 'check' ? $this->runCheck($argv) : $this->runGenerate($argv);
    }

    /**
     * @param  list<string>  $argv
     */
    private function runGenerate(array $argv): int
    {
        $options = $this->parse($argv);

        try {
            $config = $this->loadConfig($options);
            $request = $this->buildRequest($options, $config);
            $plan = (new GenerationPlanner)->plan($request);
        } catch (OptionException $e) {
            // Invalid options or config file: a configuration error exits 2
            // on every surface (artisan and standalone, generate and check).
            fwrite(STDERR, $e->getMessage()."\n");

            return self::EXIT_ERROR;
        } catch (PlanException|ParseException|GenerationException $e) {
            // A planning, spec-parse, or generation failure is a runtime failure
            // (exit 1), distinct from the configuration error above (exit 2).
            fwrite(STDERR, $e->getMessage()."\n");

            return 1;
        }

        $writer = new PlanWriter;
        $prune = isset($options['prune']) || ($config->prune ?? false);

        if ($plan->noModelSchemas) {
            fwrite(STDOUT, "No component schemas found; nothing to generate.\n");
        } else {
            $written = $writer->write($plan, PlannedFile::CATEGORY_DATA, $prune ? $request->output : null);
            fwrite(STDOUT, sprintf("Generated %d %s into %s\n", count($written), count($written) === 1 ? 'class' : 'classes', $request->output));
        }

        // The inlined runtime support classes (issue #40) live in a Support/
        // subdirectory of the Data output. Emit them here too: the artisan
        // command writes them, so the standalone binary must match or a spec that
        // references a support class (now including any closed object under the
        // default enforcement, #30) would write Data classes importing a class
        // that never landed on disk. Prune the directory on --prune so a class a
        // spec stopped using does not linger as stale, drift-flagging output.
        if ($request->output !== null && $request->output !== '') {
            $supportDir = rtrim($request->output, '/').'/Support';
            $written = $writer->write($plan, PlannedFile::CATEGORY_SUPPORT, $prune ? $supportDir : null);
            if ($written !== []) {
                fwrite(STDOUT, sprintf("Generated %d support %s into %s\n", count($written), count($written) === 1 ? 'class' : 'classes', $supportDir));
            }
        }

        if ($request->controllers) {
            $written = $writer->write($plan, PlannedFile::CATEGORY_CONTROLLER);
            fwrite(STDOUT, sprintf("Generated %d abstract %s into %s\n", count($written), count($written) === 1 ? 'controller' : 'controllers', $request->controllerPath));
        }

        if ($request->routes) {
            $written = $writer->write($plan, PlannedFile::CATEGORY_ROUTES);
            $count = count($written);
            fwrite(STDOUT, sprintf("Generated %d %s into %s\n", $count, $count === 1 ? 'route file' : 'route files', $request->routesPath));
        }

        // Non-fatal diagnostics (e.g. a non-standard per-property `required` key
        // the spec used and OpenAPI ignores) go to stderr so stdout stays clean
        // for tooling, and they do not change the success exit code.
        foreach ($plan->warnings as $warning) {
            fwrite(STDERR, 'Warning: '.$warning."\n");
        }

        return self::EXIT_OK;
    }

    /**
     * @param  list<string>  $argv
     */
    private function runCheck(array $argv): int
    {
        $options = $this->parse($argv);

        try {
            $request = $this->buildRequest($options, $this->loadConfig($options));
            $plan = (new GenerationPlanner)->plan($request);
        } catch (PlanException|OptionException|ParseException|GenerationException $e) {
            // Every failure surface of check (config error, spec parse error,
            // generation error) is the same outcome: report it and exit 2. Check
            // has no exit-2-versus-1 distinction among errors, so these collapse
            // into one arm.
            fwrite(STDERR, $e->getMessage()."\n");

            return self::EXIT_ERROR;
        }

        $entries = (new DriftChecker)->check($plan);
        $drifted = array_values(array_filter($entries, static fn (DriftEntry $entry): bool => $entry->isDrifted()));

        if ($drifted === []) {
            fwrite(STDOUT, "Generated code is in sync with the spec.\n");

            return self::EXIT_OK;
        }

        fwrite(STDOUT, sprintf("Drift detected in %d file(s):\n", count($drifted)));

        $diff = isset($options['diff']);
        $lineDiff = new LineDiff;

        foreach ($drifted as $entry) {
            $tag = $entry->status === DriftStatus::Missing ? 'missing' : 'changed';
            fwrite(STDOUT, sprintf("  [%s] %s\n", $tag, $entry->path));

            if ($diff && $entry->status === DriftStatus::Changed) {
                foreach ($lineDiff->diff($entry->expected, $entry->actual) as $line) {
                    fwrite(STDOUT, '    '.$line."\n");
                }
            }
        }

        return self::EXIT_DRIFT;
    }

    /**
     * Loads the JSON config file: the --config flag points at an explicit
     * path, otherwise `openapi-laravel.json` is discovered in the working
     * directory (absence is fine, every key falls back to a default).
     *
     * @param  array<string, string>  $options
     */
    private function loadConfig(array $options): StandaloneConfig
    {
        return (new StandaloneConfigLoader)->load($options['config'] ?? null, getcwd() ?: '.');
    }

    /**
     * Resolves every setting with strict precedence: CLI flag, then config
     * file value, then built-in default. The scaffold output paths default to
     * deterministic locations under the model output directory
     * (`<output>/Controllers` and `<output>/routes.php`) so the full-output
     * default needs no extra flags.
     *
     * @param  array<string, string>  $options
     */
    private function buildRequest(array $options, StandaloneConfig $config): GenerationRequest
    {
        $spec = $options['spec'] ?? $config->spec;
        $output = $options['output'] ?? $config->outputPath;

        if ($spec === null || $output === null) {
            throw new PlanException(trim($this->usage()));
        }

        $namespace = $options['namespace'] ?? $config->namespace ?? 'App\\Data';
        $suffix = $options['suffix'] ?? $config->suffix ?? 'Data';
        $maxDepth = isset($options['max-depth']) ? (int) $options['max-depth'] : ($config->maxDepth ?? 64);
        $maxBytes = isset($options['max-bytes']) ? (int) $options['max-bytes'] : $config->maxBytes;

        $controllers = $this->resolveToggle($options, 'controllers', $config->controllersEnabled);
        $routes = $this->resolveToggle($options, 'routes', $config->routesEnabled);

        // Closed-object enforcement is a default-on toggle, resolved with the
        // same strict precedence as controllers/routes: flag beats the config
        // file key, the config file key beats the built-in default (enabled).
        // Both --enforce-closed-objects and --no-enforce-closed-objects at once
        // is a contradiction that fails loudly (exit 2).
        $enforceClosedObjects = $this->resolveToggle($options, 'enforce-closed-objects', $config->enforceClosedObjectsEnabled);

        $outputDir = rtrim($output, '/');
        $controllerOutput = $options['controller-output'] ?? $config->controllerPath ?? $outputDir.'/Controllers';
        $routesOutput = $options['routes-output'] ?? $config->routesPath ?? $outputDir.'/routes.php';
        $controllerNamespace = $options['controller-namespace'] ?? $config->controllerNamespace ?? 'App\\Http\\Controllers\\Api';

        // Subset generation (issue #44): the comma-separated flag wins over the
        // config key, which may itself be a comma string or a list. Empty means
        // "full spec". The closure is resolved later in the planner.
        $onlyTags = $this->resolveList($options, 'only-tags', $config->onlyTags);
        $onlySchemas = $this->resolveList($options, 'only-schemas', $config->onlySchemas);

        // Route group settings (issue #71). Config-only by design, no CLI
        // flags: routes.middleware and routes.prefix wrap the generated routes
        // in one Route::group block. A whitespace-only prefix means "no
        // prefix" so it can never emit a useless group wrapper.
        $routesMiddleware = $config->routesMiddleware ?? [];
        $routesPrefix = $config->routesPrefix !== null && trim($config->routesPrefix) !== ''
            ? trim($config->routesPrefix)
            : null;

        return new GenerationRequest(
            $spec,
            $output,
            $namespace,
            $suffix,
            $maxDepth,
            $maxBytes,
            $controllers,
            $controllerOutput,
            $controllerNamespace,
            $routes,
            $routesOutput,
            $enforceClosedObjects,
            $onlyTags,
            $onlySchemas,
            $routesMiddleware,
            $routesPrefix,
        );
    }

    /**
     * Resolve a subset list (issue #44): the comma-separated CLI flag overrides
     * the config-file value (already normalized to a list by the loader). Returns
     * [] when neither is set, which the planner reads as "no subset".
     *
     * @param  array<string, string>  $options
     * @param  list<string>|null  $configured
     * @return list<string>
     */
    private function resolveList(array $options, string $flag, ?array $configured): array
    {
        $flagValue = $options[$flag] ?? null;
        if (is_string($flagValue) && trim($flagValue) !== '') {
            $names = [];
            foreach (explode(',', $flagValue) as $part) {
                $part = trim($part);
                if ($part !== '') {
                    $names[] = $part;
                }
            }

            return $names;
        }

        return $configured ?? [];
    }

    /**
     * Resolves an enable/disable flag pair against the config file: flag beats
     * config, config beats the built-in default (enabled). Both flags at once
     * is a contradiction the operator must resolve, so it fails loudly.
     *
     * @param  array<string, string>  $options
     *
     * @throws OptionException when both --{$name} and --no-{$name} are passed
     */
    private function resolveToggle(array $options, string $name, ?bool $configured): bool
    {
        $enable = isset($options[$name]);
        $disable = isset($options['no-'.$name]);

        if ($enable && $disable) {
            throw new OptionException(sprintf('--%s and --no-%s cannot be combined. Pass at most one of them.', $name, $name));
        }

        if ($enable) {
            return true;
        }

        if ($disable) {
            return false;
        }

        return $configured ?? true;
    }

    /**
     * Peels an optional leading subcommand off argv (after the program name),
     * returning the subcommand (or null) and the argv with it removed so the
     * option parser sees the same shape regardless of which subcommand ran.
     *
     * @param  list<string>  $argv
     * @return array{0: ?string, 1: list<string>}
     */
    private function splitSubcommand(array $argv): array
    {
        $program = $argv[0] ?? 'openapi-laravel';
        $rest = array_slice($argv, 1);

        if (isset($rest[0]) && ($rest[0] === 'check' || $rest[0] === 'generate')) {
            $subcommand = $rest[0];
            $rest = array_slice($rest, 1);

            return [$subcommand, array_values([$program, ...$rest])];
        }

        return [null, array_values([$program, ...$rest])];
    }

    /**
     * @param  list<string>  $argv
     * @return array<string, string>
     */
    private function parse(array $argv): array
    {
        $options = [];

        foreach (array_slice($argv, 1) as $argument) {
            if (! str_starts_with($argument, '--')) {
                continue;
            }

            $body = substr($argument, 2);
            $position = strpos($body, '=');

            if ($position === false) {
                $options[$body] = '1';
            } else {
                $options[substr($body, 0, $position)] = substr($body, $position + 1);
            }
        }

        return $options;
    }

    private function usage(): string
    {
        return <<<'TXT'
        openapi-laravel - generate Laravel models, controllers, and routes from an OpenAPI spec

        Usage:
          openapi-laravel [generate] --spec=<path> --output=<dir> [options]
          openapi-laravel check --spec=<path> --output=<dir> [options]

        Commands:
          generate             Write the generated files (default)
          check                Verify the files on disk match the spec (CI drift gate)

        Settings resolve with strict precedence: flags beat the config file,
        the config file beats the built-in defaults. The config file is
        openapi-laravel.json in the working directory (if present), or the
        path given via --config. Its keys mirror config/openapi-laravel.php:
        spec, output.{path,namespace,suffix,prune}, controllers.{enabled,path,
        namespace}, routes.{enabled,path,middleware,prefix}, enforce_closed_objects,
        max_depth, max_bytes, only_tags, only_schemas (the only_* keys each a
        comma-separated string or a JSON list of names). routes.middleware (a JSON
        list of names, never comma-split) and routes.prefix wrap the generated
        routes in one Route::group block; they are config-only, with no CLI flags.

        Options:
          --config=<path>      Path to a JSON config file (default: ./openapi-laravel.json)
          --spec=<path>        Path to the OpenAPI document (required unless set in config)
          --output=<dir>       Output directory for generated classes (required unless set in config)
          --namespace=<ns>     Namespace for generated classes (default: App\Data)
          --suffix=<suffix>    Data class name suffix (default: Data)
          --max-depth=<n>      Maximum schema nesting depth (default: 64)
          --prune              Delete existing .php files in the output dir first (generate only)
          --enforce-closed-objects     Reject unknown keys for additionalProperties: false schemas (default: on)
          --no-enforce-closed-objects  Accept unknown keys even for additionalProperties: false schemas
          --only-tags=<list>   Generate only operations carrying these comma-separated tags, plus their schema closure
          --only-schemas=<list> Generate only these comma-separated component schemas, plus their dependency closure
          --diff               Print a unified diff for each changed file (check only)

        Server scaffold (generated by default):
          --no-controllers               Skip the abstract controllers
          --no-routes                    Skip the routes file
          --controllers                  Force controllers on (overrides a config that disables them)
          --routes                       Force the routes file on (overrides a config that disables it)
          --controller-output=<dir>      Where the abstract controllers live (default: <output>/Controllers)
          --controller-namespace=<ns>    Controller namespace (default: App\Http\Controllers\Api)
          --routes-output=<file>         Where the routes file lives (default: <output>/routes.php)

        Exit codes:
          0  success / in sync
          1  drift detected (check) or a generate error
          2  invalid options or config file (generate and check), or a spec error in check

        TXT;
    }
}
